---
SPELL_CSPELL_DISABLE_ERRORS: true
JAVA_CHECKSTYLE_FILTER_REGEX_EXCLUDE: generated
COPYPASTE_JSCPD_DISABLE_ERRORS_IF_LESS_THAN: 2
DISABLE:
  - MARKDOWN
  - SPELL
DISABLE_LINTERS:
  - REPOSITORY_SEMGREP
  - CLOJURE_CLJSTYLE
