name: "GitHub CI"

on:
  pull_request:
    branches: [ master ]

jobs:
  clj-kondo:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Run clj-kondo
        run: >-
          docker run
          --volume "$PWD:/work"
          --rm
          cljkondo/clj-kondo:2023.05.18-alpine
          clj-kondo
          --config /work/.clj-kondo/config.edn
          --config-dir /work/.clj-kondo
          --parallel
          --lint
          /work/src
          /work/test

  cljstyle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Check with cljstyle
        run: >-
          docker run
          --volume "$PWD:/work"
          --rm
          abogoyavlensky/cljstyle:0.15.0
          cljstyle check --report /work

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          distribution: zulu
          java-version: 17

      - name: Restore local Maven repository from cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles( 'project.clj' ) }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate proto files
        run: lein protodeps generate

      - name: Build uberjar
        run: lein uberjar

  test:
    needs:
      - build
      - clj-kondo
      - cljstyle
      - megalinter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          distribution: zulu
          java-version: 17

      - name: Restore local Maven repository from cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles( 'project.clj' ) }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate proto files
        run: lein protodeps generate

      - name: Unit tests
        env:
          IP_STACK_ACCESS_KEY: ${{ secrets.IP_STACK_ACCESS_KEY }}
        run: lein cloverage --html --lcov --junit

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.40
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "target/coverage/junit.xml"

      - name: Coveralls
        uses: coverallsapp/github-action@v2.1.2
        with:
          path-to-lcov: "target/coverage/lcov.info"
          github-token: ${{ secrets.GITHUB_TOKEN }}
