name: "GitHub CI"

on:
  pull_request:
    branches: [master]

jobs:
  cancel_duplicates:
    name: Cancel duplicate jobs
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Restore local Maven repository from cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles( 'project.clj' ) }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate proto files
        run: lein protodeps generate

      - name: Run linters
        run: lein do clean, lint, cljstyle check

      - name: Build uberjar
        run: lein uberjar

      - name: Mega-Linter
        id: ml
        uses: nvuillam/mega-linter/flavors/java@v5
        env:
          # All available variables are described in documentation
          # https://nvuillam.github.io/mega-linter/configuration/
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }} # Validates all source when push on master, else just the git diff with master. Override with true if you always want to lint all sources
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE: MARKDOWN,SPELL
          JAVA_CHECKSTYLE_FILTER_REGEX_EXCLUDE: generated
          CLOJURE_CLJ_KONDO_FILTER_REGEX_INCLUDE: (src|lib)

      # Upload Mega-Linter artifacts
      - name: Archive production artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Mega-Linter reports
          path: |
            report
            mega-linter.log

  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Restore local Maven repository from cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles( 'project.clj' ) }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate proto files
        run: lein protodeps generate

      - name: Unit tests
        env:
          IP_STACK_ACCESS_KEY: ${{ secrets.IP_STACK_ACCESS_KEY }}
        run: lein cloverage --html --lcov --junit

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.25
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "target/coverage/junit.xml"

      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          path-to-lcov: "target/coverage/lcov.info"
          github-token: ${{ secrets.GITHUB_TOKEN }}
