---
name: "GitHub CI"

permissions:
  contents: read
  pull-requests: write
  actions: read
  issues: read
  discussions: write
  repository-projects: write
  checks: write

on:
  pull_request:
    branches: [master]

jobs:
  clj-kondo:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    services:
      clj-kondo:
        image: cljkondo/clj-kondo:2023.05.18-alpine
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Run clj-kondo
        run: >-
          clj-kondo
          --config /work/.clj-kondo/config.edn
          --config-dir /work/.clj-kondo
          --parallel
          --lint

  cljstyle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Check with cljstyle
        run: >-
          docker run
          --volume "$PWD:/work"
          --rm
          abogoyavlensky/cljstyle:0.15.0
          cljstyle check --report /work

  megalinter:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Mega-Linter
        id: ml
        uses: nvuillam/mega-linter/flavors/java@v6.22.2
        env:
          # All available variables are described in documentation
          # https://nvuillam.github.io/mega-linter/configuration/
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }} # Validates all source when push on master, else just the git diff with master. Override with true if you always want to lint all sources
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE: MARKDOWN,SPELL
          DISABLE_LINTERS: REPOSITORY_SEMGREP
          JAVA_CHECKSTYLE_FILTER_REGEX_EXCLUDE: generated
          CLOJURE_CLJ_KONDO_FILTER_REGEX_INCLUDE: (src|lib)
          COPYPASTE_JSCPD_DISABLE_ERRORS_IF_LESS_THAN: 2

      # Upload Mega-Linter artifacts
      - name: Archive production artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Mega-Linter reports
          path: |
            report
            mega-linter.log

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          distribution: zulu
          java-version: 17

      - name: Restore local Maven repository from cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles( 'project.clj' ) }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate proto files
        run: lein protodeps generate

      - name: Build uberjar
        run: lein uberjar

  test:
    needs:
      - build
      - clj-kondo
      - cljstyle
      - megalinter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          distribution: zulu
          java-version: 17

      - name: Restore local Maven repository from cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles( 'project.clj' ) }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate proto files
        run: lein protodeps generate

      - name: Unit tests
        env:
          IP_STACK_ACCESS_KEY: ${{ secrets.IP_STACK_ACCESS_KEY }}
        run: lein cloverage --html --lcov --junit

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.40
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "target/coverage/junit.xml"

      - name: Coveralls
        uses: coverallsapp/github-action@v2.1.2
        with:
          path-to-lcov: "target/coverage/lcov.info"
          github-token: ${{ secrets.GITHUB_TOKEN }}
